enum States {
    LOADING = "LOADING",
    READY = "READY",
    NOTAUTHORIZED = "NOTAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    ERROR = "ERROR",
    NOTFOUND = "NOTFOUND",
    UPDATING = "UPDATING",
    OFFLINE = "OFFLINE",
    NOTINITIATED = "NOTINITIATED",
    VALIDATIONERROR = "VALIDATIONERROR",
}

export default States;
